#!/bin/bash

# CREATED A TRASH BIN IF ONE IS NOT DEFINED AS A SORT OF SANITY CHECK

if [[ -z "${TRASH}" ]]
then
        # TRASH directory path was not defined
        # makes a safe trash directory in CWD, if one doesn't exist yet
        trash=$(pwd) # gets current working directory path
        trash+="/TRASH/" # adds the new trash dir to path
        mkdir -p TRASH

        # I CHOSE NOT TO EXPORT AN ENV CALLED TRASH SINCE
        # THE USER MIGHT HAVE TO SOURCE THIS SCRIPT WHEN RUNNING
        # AND I DON'T WANT TO MODIFY OTHERS' SHELL PROFILES
else
        # A "TRASH" ENVIRONMENT VARIABLE WAS FOUND & DEFINED
        trash=${TRASH} # sets our trash directory to the provided one
fi

# If the trash directory does not exist, prints an error message

if [ -d $trash ]
then
        echo "Here's how much disk space of all the files in trash, not including TRASH itself:"
	du -hc TRASH/* | grep total
else
        echo "The trash directory path provided from the enviroment variable TRASH"
        echo "does not exists."
fi
